### ISSUE TITLE
sendmail SUID

### ISSUE THREAD

**Issue by drzraf** [shuber2/smailq#2]
Shell script are most often not allowed to be setuid.
But the consequence of smailq' sendmail not being SUID is that it can't call to `msmtp` for users other than root because `msmtp` checks whether the owner is the same as `geteuid()` and, if yes, enforce 0600 permissions (https://github.com/marlam/msmtp-mirror/issues/35)

For smailq to work with multiple senders (daemons, users, ...), smailq's `sendmail` must be made SUID.

The only solution seems to make it a compiled binary but the SUID would not be passed-on to underlying (Python) smailq script neither its `subprocess.call()`. Could compiling the code to a native binary be an possible solution?

With `nuitka3 --standalone  smailq`, we can get a 7.8MB standalone native binary.
`smailq`' Python could also check whether it's been called as `sendmail` and process accordingly (and the Python compiled version would be SUID)

**Comment by shuber2** [comment]
According to the discussion on marlam/msmtp-mirror#35 this should not be an issue for system-wide msmtp configurations of msmtp, which you are  using. Can you comment on the progress of this discussion? In particular, does it resolve this issue as well?

**Comment by drzraf** [comment]
Yes. The msmtp situation can be resolved by omitting `-C` but it needs to be made "o+r" which is not ideal given it's likely to contains sensitive credentials.


But I come over another problematic situation.

- `php` exec() `sendmail` (being `www-data` or anything else)
- `sendmail` point to `smailq`
- `smailq` try to create a file within the datadir

Currently: It fails (unless you give `o+w` or the `sticky bit` to the datadir.
Using a set-UID the binary: It would work create the files naturally and not force /etc/msmtprc to be world-readable.

**Comment by shuber2** [comment]
I am very reluctant of setting `suid` from a security point of view. Before making such a step the question is whether a different software design would fix this.

However, why would not you configure smailq for user www-data? Its home directory is /var/www on Debian systems, for instance. In the meanwhile I would like to close this issue.

**Comment by drzraf** [comment]
Because it's not actually Apache anymore but PHP daemons which are running it and I happen to have multiple PHP daemons under different users and would rather not play with ACL for this.
And since I don't see any socket/protocol based solution, I end up with this.
Do you see any alternatives?
